# urls.py (updated)
from django.urls import path
from .views import (
                   CenterLoginAPIView,AddAdministrativeStaffAPIView,AddMedicalStaffAPIView,AddParamedicalStaffAPIView,
                   AddTechnicalStaffAPIView,AddWorkerStaffAPIView,AddPatientAPIView,
                   DeclareDeceasedAPIView,AddComplicationsAPIView,AddHemodialysisSessionAPIView,
                   AddTransmittableDiseaseAPIView,AddTransplantationAPIView,AddComplicationsRefAPIView,
                   AddTransmittableDiseaseRefAPIView,AddTransplantationRefAPIView,AddMachineAPIView,UserProfileView,
                   PatientsView,PatientMedicalActivityView,PatientDetailAPIView,MedicalStaffAPIView ,TypeHemoAPIView,
                   MethodHemoAPIView,TransmittableDiseaseRefAPIView,TransplantationRefAPIView,ComplicationsRefAPIView,
                   CNAMListAPIView,AdministrativeStaffListAPIView,ParamedicalStaffListAPIView,MedicalStaffListAPIView,WorkerStaffListAPIView
                   ,TechnicalStaffListAPIView,UpdateAdministrativeStaffAPIView,UpdateMedicalStaffAPIView,UpdateParamedicalStaffAPIView
                   ,UpdateAdministrativeStaffAPIView,UpdateTechnicalStaffAPIView,UpdateWorkerStaffAPIView,DeleteAdministrativeStaffAPIView,DeleteMedicalStaffAPIView
                   ,DeleteParamedicalStaffAPIView,DeleteTechnicalStaffAPIView,DeleteWorkerStaffAPIView,MachineListAPIView,
                     MembraneListAPIView,ExportPDFAPIView, FiltreListAPIView,AddFiltreAPIView,AddMembraneAPIView,
                     VerifyUserAPIView,UpdateMachineAPIView,DeleteMachineAPIView,
                     UpdateUserProfileAPIView,CenterDetailView,HemodialysisPredictionView,GrantAdminAccordAPIView, MedicalStaffDetailAPIView, WorkerStaffDetailAPIView, ParamedicalStaffDetailAPIView,
    AdministrativeStaffDetailAPIView, TechnicalStaffDetailAPIView,UserDetailsAPIView
                   )
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [

    path('api/login/', CenterLoginAPIView.as_view(), name='center_login_api'),
    path('api/add-administrative-staff/', AddAdministrativeStaffAPIView.as_view(), name='add_administrative_staff_api'),
    path('api/add-technical-staff/', AddTechnicalStaffAPIView.as_view(), name='add_technical_staff_api'),
    path('api/add-medical-staff/', AddMedicalStaffAPIView.as_view(), name='add_medical_staff_api'),
    path('api/add-paramedical-staff/', AddParamedicalStaffAPIView.as_view(), name='add_paramedical_staff_api'),
    path('api/add-worker-staff/', AddWorkerStaffAPIView.as_view(), name='add_worker_staff_api'),
    path('api/add-patient/', AddPatientAPIView.as_view(), name='add_patient_api'),
    path('api/declare-deceased/<int:patient_id>/', DeclareDeceasedAPIView.as_view(), name='declare_deceased_api'),
    path('api/add-hemodialysis-session/<int:patient_id>/', AddHemodialysisSessionAPIView.as_view(), name='add_hemodialysis_session_api'),
    path('api/add-transmittable-disease/<int:patient_id>/', AddTransmittableDiseaseAPIView.as_view(), name='add_transmittable_disease_api'),
    path('api/add-complications/<int:patient_id>/', AddComplicationsAPIView.as_view(), name='add_complications_api'),
    path('api/add-transplantation/<int:patient_id>/', AddTransplantationAPIView.as_view(), name='add_transplantation_api'),
    path('api/add-transmittable-disease-ref/', AddTransmittableDiseaseRefAPIView.as_view(), name='add-transmittable-disease-ref'),
    path('api/add-complications-ref/', AddComplicationsRefAPIView.as_view(), name='add-complications-ref'),
    path('api/add-transplantation-ref/', AddTransplantationRefAPIView.as_view(), name='add-transplantation-ref'),
    path('api/add-machine/', AddMachineAPIView.as_view(), name='add-machine'),
    path('api/user-profile/', UserProfileView.as_view(), name='user-profile'),
    path('api/patients/', PatientsView.as_view(), name='patients'),
    path('api/patients/<int:patient_id>/medical-activity/', PatientMedicalActivityView.as_view(), name='patient-medical-activity'),
    path('api/patients/<int:patient_id>/', PatientDetailAPIView.as_view(), name='patient-detail'),
    path('api/type-hemo/', TypeHemoAPIView.as_view(), name='type_hemo_list'),
    path('api/method-hemo/', MethodHemoAPIView.as_view(), name='method_hemo_list'),
    path('api/transmittable-disease-ref/', TransmittableDiseaseRefAPIView.as_view(), name='transmittable_disease_ref'),
    path('api/complications-ref/', ComplicationsRefAPIView.as_view(), name='complications_ref'),
    path('api/transplantation-ref/', TransplantationRefAPIView.as_view(), name='transplantation_ref'),
    path('api/cnams/', CNAMListAPIView.as_view(), name='cnam_list_api'),
    path('api/administrative-staff/', AdministrativeStaffListAPIView.as_view(), name='administrative_staff_list_api'),
    path('api/medical-staff/', MedicalStaffListAPIView.as_view(), name='medical_staff_list_api'),
    path('api/paramedical-staff/', ParamedicalStaffListAPIView.as_view(), name='paramedical_staff_list_api'),
    path('api/technical-staff/', TechnicalStaffListAPIView.as_view(), name='technical_staff_list_api'),
    path('api/worker-staff/', WorkerStaffListAPIView.as_view(), name='worker_staff_list_api'),
    path('api/update-medical-staff/<int:pk>/', UpdateMedicalStaffAPIView.as_view(), name='update-medical-staff'),
    path('api/delete-medical-staff/<int:pk>/', DeleteMedicalStaffAPIView.as_view(), name='delete-medical-staff'),
    path('api/update-paramedical-staff/<int:pk>/', UpdateParamedicalStaffAPIView.as_view(), name='update-paramedical-staff'),
    path('api/delete-paramedical-staff/<int:pk>/', DeleteParamedicalStaffAPIView.as_view(), name='delete-paramedical-staff'),
    path('api/update-administrative-staff/<int:pk>/', UpdateAdministrativeStaffAPIView.as_view(), name='update-administrative-staff'),
    path('api/delete-administrative-staff/<int:pk>/', DeleteAdministrativeStaffAPIView.as_view(), name='delete-administrative-staff'),
    path('api/update-worker-staff/<int:pk>/', UpdateWorkerStaffAPIView.as_view(), name='update-worker-staff'),
    path('api/delete-worker-staff/<int:pk>/', DeleteWorkerStaffAPIView.as_view(), name='delete-worker-staff'),
    path('api/update-technical-staff/<int:pk>/', UpdateTechnicalStaffAPIView.as_view(), name='update-technical-staff'),
    path('api/delete-technical-staff/<int:pk>/', DeleteTeachnicalStaffAPIView.as_view(), name='delete-technical-staff'),
    path('api/machines/', MachineListAPIView.as_view(), name='machine-list'),
    path('api/membranes/', MembraneListAPIView.as_view(), name='membrane-list'),
    path('api/filtres/', FiltreListAPIView.as_view(), name='filtre-list'),
    path('api/add-filtre/', AddFiltreAPIView.as_view(), name='add-filtre'),
    path('api/add-membrane/', AddMembraneAPIView.as_view(), name='add-membrane'),
    path('api/verify-user/', VerifyUserAPIView.as_view(), name='verify_user'),
    path('api/update-profile/', UpdateUserProfileAPIView.as_view(), name='update_user_profile'),
    path('api/export-pdf/', ExportPDFAPIView.as_view(), name='export-pdf'),
    path('api/center-details/', CenterDetailView.as_view(), name='center-details'),
    path('api/predict-hemodialysis/', HemodialysisPredictionView.as_view(), name='predict-hemodialysis'),
    path('api/grant-accord/',GrantAdminAccordAPIView.as_view(),name='grant-accord'),
    path('api/machines/<int:machine_id>/update/', UpdateMachineAPIView.as_view(), name='update-machine'),
    path('api/machines/<int:machine_id>/delete/', DeleteMachineAPIView.as_view(), name='delete-machine'),
    path('api/medical-staff/<int:staff_id>/', MedicalStaffDetailAPIView.as_view(), name='medical-staff-detail'),
    path('api/worker-staff/<int:staff_id>/', WorkerStaffDetailAPIView.as_view(), name='worker-staff-detail'),
    path('api/paramedical-staff/<int:staff_id>/', ParamedicalStaffDetailAPIView.as_view(), name='paramedical-staff-detail'),
    path('api/administrative-staff/<int:staff_id>/', AdministrativeStaffDetailAPIView.as_view(), name='administrative-staff-detail'),
    path('api/technical-staff/<int:staff_id>/', TechnicalStaffDetailAPIView.as_view(), name='technical-staff-detail'),
    path('api/user/details/', UserDetailsAPIView.as_view(), name='user-details'),
]