# Generated by Django 4.2 on 2025-04-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='mail',
            field=models.EmailField(default='default@def.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='center',
            name='state',
            field=models.CharField(default='default@default.com', max_length=100),
            preserve_default=False,
        ),
    ]
