# Generated by Django 4.2 on 2025-04-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_center_mail_center_private_center_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='nom',
            new_name='label',
        ),
        migrations.AddField(
            model_name='center',
            name='code_type_hemo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='delegate_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='government_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='name_delegate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='name_type_hemo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='type_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
