# Generated by Django 4.2 on 2025-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_governorate_delegation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
