# Generated by Django 4.2 on 2025-05-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_remove_center_government_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='delegate_code',
        ),
    ]
