# Generated by Django 4.2 on 2025-05-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_remove_center_delegate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_code',
            field=models.IntegerField(null=True),
        ),
    ]
