# Generated by Django 4.2 on 2025-05-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_center_center_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='private',
        ),
        migrations.AlterField(
            model_name='center',
            name='code_type_hemo',
            field=models.CharField(blank=True, default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='center',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.delegation'),
        ),
        migrations.AlterField(
            model_name='center',
            name='governorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.governorate'),
        ),
        migrations.AlterField(
            model_name='center',
            name='name_type_hemo',
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='center',
            name='tel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='center',
            name='type_center',
            field=models.CharField(choices=[('CIRCONSCRIPTION', 'Circonscription Hospital'), ('REGIONAL', 'Regional Hospital'), ('UNIVERSITY', 'University Hospital'), ('BASIC', 'Basic health group'), ('PRIVATE', 'Private')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
