# Generated by Django 4.2 on 2025-05-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0009_remove_center_private_alter_center_code_type_hemo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='code_type_hemo',
            field=models.CharField(blank=True, choices=[('MD2200', 'MD2200'), ('UNITE', 'UNITE'), ('UNITEP', 'UNITEP')], max_length=10),
        ),
        migrations.AlterField(
            model_name='center',
            name='name_type_hemo',
            field=models.CharField(blank=True, choices=[('SERVICE HEMODIALYSE', 'SERVICE HEMODIALYSE'), ('UNITE HEMODIALYSE', 'UNITE HEMODIALYSE'), ('UNITE HEMODIALYSE PEDIATRIQUE', 'UNITE HEMODIALYSE PEDIATRIQUE')], max_length=30),
        ),
    ]
