# Generated by Django 4.2 on 2025-05-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0010_alter_center_code_type_hemo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('sterilisation', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membrane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('functional', models.BooleanField(default=True)),
                ('reserve', models.BooleanField(default=False)),
                ('refurbished', models.BooleanField(default=False)),
                ('nbre_hrs', models.IntegerField(default=0)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='centers.center')),
                ('filtre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.filtre')),
                ('membrane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.membrane')),
            ],
        ),
    ]
