# Generated by Django 4.2 on 2025-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0011_filtre_membrane_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='adresse',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
