# Generated by Django 4.2 on 2025-05-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0012_center_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='center',
            name='tel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterModelTable(
            name='medicalstaff',
            table='centers_medicalstaff',
        ),
        migrations.AlterModelTable(
            name='paramedicalstaff',
            table='centers_paramedicalstaff',
        ),
        migrations.AlterModelTable(
            name='technicalstaff',
            table='centers_technicalstaff',
        ),
        migrations.CreateModel(
            name='WorkerStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=50, unique=True)),
                ('job_title', models.CharField(max_length=100)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_staff', to='centers.center')),
            ],
            options={
                'db_table': 'centers_workerstaff',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=50, unique=True)),
                ('CNAM', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_staff', to='centers.center')),
            ],
            options={
                'db_table': 'centers_patient',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_staff', to='centers.center')),
            ],
            options={
                'db_table': 'centers_administrativestaff',
            },
        ),
    ]
