# Generated by Django 4.2 on 2025-05-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0013_alter_center_mail_alter_center_tel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'centers_cnam',
            },
        ),
        migrations.RemoveField(
            model_name='patient',
            name='CNAM',
        ),
        migrations.AddField(
            model_name='patient',
            name='cnam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='centers.cnam'),
            preserve_default=False,
        ),
    ]
