# Generated by Django 4.2 on 2025-05-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0016_medicalactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeHemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'centers_typehemo',
            },
        ),
        migrations.CreateModel(
            name='MethodHemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_hemo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='centers.typehemo')),
            ],
            options={
                'db_table': 'centers_methodhemo',
                'unique_together': {('type_hemo', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HemodialysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_session', models.DateField()),
                ('medical_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hemodialysis_sessions', to='centers.medicalactivity')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.methodhemo')),
                ('responsible_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.medicalstaff')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.typehemo')),
            ],
            options={
                'db_table': 'centers_hemodialysissession',
            },
        ),
    ]
