# Generated by Django 4.2 on 2025-05-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0017_typehemo_methodhemo_hemodialysissession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmittableDiseaseRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_disease', models.CharField(max_length=100, unique=True)),
                ('type_of_transmission', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'centers_transmittablediseaseref',
            },
        ),
        migrations.CreateModel(
            name='TransmittableDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_contraction', models.DateField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.transmittablediseaseref')),
                ('medical_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmittable_diseases', to='centers.medicalactivity')),
            ],
            options={
                'db_table': 'centers_transmittabledisease',
            },
        ),
    ]
