# Generated by Django 4.2 on 2025-05-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0018_transmittablediseaseref_transmittabledisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplicationsRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_complication', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'centers_complicationsref',
            },
        ),
        migrations.CreateModel(
            name='Complications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('date_of_contraction', models.DateField()),
                ('complication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.complicationsref')),
                ('medical_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complications', to='centers.medicalactivity')),
            ],
            options={
                'db_table': 'centers_complications',
            },
        ),
    ]
