# Generated by Django 4.2 on 2025-05-10 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centers', '0019_complicationsref_complications'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativestaff',
            name='job_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrativestaff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrative_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='role',
            field=models.CharField(choices=[('LOCAL_ADMIN', 'Local Admin'), ('SUBMITTER', 'Submitter'), ('MEDICAL_PARA_STAFF', 'Medical & Paramedical Staff'), ('VIEWER', 'Viewer')], default='MEDICAL_PARA_STAFF', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paramedicalstaff',
            name='role',
            field=models.CharField(choices=[('LOCAL_ADMIN', 'Local Admin'), ('SUBMITTER', 'Submitter'), ('MEDICAL_PARA_STAFF', 'Medical & Paramedical Staff'), ('VIEWER', 'Viewer')], default='MEDICAL_PARA_STAFF', max_length=20),
        ),
        migrations.AddField(
            model_name='paramedicalstaff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paramedical_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalstaff',
            name='role',
            field=models.CharField(choices=[('LOCAL_ADMIN', 'Local Admin'), ('SUBMITTER', 'Submitter'), ('MEDICAL_PARA_STAFF', 'Medical & Paramedical Staff'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
        migrations.AddField(
            model_name='technicalstaff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workerstaff',
            name='role',
            field=models.CharField(choices=[('LOCAL_ADMIN', 'Local Admin'), ('SUBMITTER', 'Submitter'), ('MEDICAL_PARA_STAFF', 'Medical & Paramedical Staff'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
        migrations.AddField(
            model_name='workerstaff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='administrativestaff',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_staff', to='centers.center'),
        ),
        migrations.AlterField(
            model_name='administrativestaff',
            name='role',
            field=models.CharField(choices=[('LOCAL_ADMIN', 'Local Admin'), ('SUBMITTER', 'Submitter'), ('MEDICAL_PARA_STAFF', 'Medical & Paramedical Staff'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_staff', to='centers.center'),
        ),
        migrations.AlterField(
            model_name='paramedicalstaff',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paramedical_staff', to='centers.center'),
        ),
        migrations.AlterField(
            model_name='technicalstaff',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_staff', to='centers.center'),
        ),
        migrations.AlterField(
            model_name='workerstaff',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_staff', to='centers.center'),
        ),
    ]
