# Generated by Django 4.2 on 2025-05-12 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centers', '0020_administrativestaff_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativestaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paramedicalstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paramedical_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technicalstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
