# Generated by Django 4.2 on 2025-05-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0022_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransplantationRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_transplantation', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'centers_transplantationref',
            },
        ),
        migrations.AlterField(
            model_name='filtre',
            name='sterilisation',
            field=models.CharField(blank=True, choices=[('WATER_STEAM', 'Water Steam'), ('GAMMA_RAYS', 'Gamma Rays'), ('ETHYLENE_OXIDE', 'Ethylene Oxide')], max_length=100),
        ),
        migrations.CreateModel(
            name='Transplantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('medical_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transplantations', to='centers.medicalactivity')),
                ('transplantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.transplantationref')),
            ],
            options={
                'db_table': 'centers_transplantation',
            },
        ),
    ]
