# Generated by Django 4.2 on 2025-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0025_patient_age_patient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='decease_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('ALIVE', 'Alive'), ('DECEASED', 'Deceased')], default='ALIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
