# Generated by Django 4.2 on 2025-05-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0026_patient_decease_note_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemodialysissession',
            name='during_dialysis_bp',
            field=models.FloatField(blank=True, help_text='During-dialysis blood pressure (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='heart_rate',
            field=models.FloatField(blank=True, help_text='Heart rate (beats per minute)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='post_dialysis_bp',
            field=models.FloatField(blank=True, help_text='Post-dialysis blood pressure (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='pre_dialysis_bp',
            field=models.FloatField(blank=True, help_text='Pre-dialysis blood pressure (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetes',
            field=models.BooleanField(default=False, help_text='Indicates if the patient has diabetes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hypertension',
            field=models.BooleanField(default=False, help_text='Indicates if the patient has hypertension'),
        ),
    ]
