# Generated by Django 4.2 on 2025-05-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0027_hemodialysissession_during_dialysis_bp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemodialysissession',
            name='albumin',
            field=models.FloatField(blank=True, help_text='Albumin level (g/dL)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='creatinine',
            field=models.FloatField(blank=True, help_text='Creatinine level (mg/dL)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='dialysis_duration',
            field=models.FloatField(blank=True, help_text='Dialysis duration (hours)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='dialyzer_type',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Low', 'Low')], help_text='Type of dialyzer', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='dry_weight',
            field=models.FloatField(blank=True, help_text='Dry weight (kg)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='fluid_removal_rate',
            field=models.FloatField(blank=True, help_text='Fluid removal rate (mL/hour)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='hematocrit',
            field=models.FloatField(blank=True, help_text='Hematocrit level (%)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='hemoglobin',
            field=models.FloatField(blank=True, help_text='Hemoglobin level (g/dL)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='kt_v',
            field=models.FloatField(blank=True, help_text='Kt/V (dialysis adequacy)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='potassium',
            field=models.FloatField(blank=True, help_text='Potassium level (mEq/L)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='severity_of_case',
            field=models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], help_text='Severity of the case', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='urea',
            field=models.FloatField(blank=True, help_text='Urea level (mg/dL)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='urine_output',
            field=models.FloatField(blank=True, help_text='Urine output (mL/day)', null=True),
        ),
        migrations.AddField(
            model_name='hemodialysissession',
            name='vascular_access_type',
            field=models.CharField(blank=True, choices=[('Catheter', 'Catheter'), ('Graft', 'Graft'), ('Fistula', 'Fistula')], help_text='Type of vascular access', max_length=20, null=True),
        ),
    ]
