# Generated by Django 4.2 on 2025-05-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0028_hemodialysissession_albumin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativestaff',
            name='role',
            field=models.CharField(choices=[('LOCAL_ADMIN', 'Local Admin'), ('SUBMITTER', 'Submitter'), ('MEDICAL_PARA_STAFF', 'Medical & Paramedical Staff'), ('VIEWER', 'Viewer'), ('TECHNICAL', 'Technical')], default='VIEWER', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='role',
            field=models.CharField(choices=[('LOCAL_ADMIN', 'Local Admin'), ('SUBMITTER', 'Submitter'), ('MEDICAL_PARA_STAFF', 'Medical & Paramedical Staff'), ('VIEWER', 'Viewer'), ('TECHNICAL', 'Technical')], default='MEDICAL_PARA_STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='paramedicalstaff',
            name='role',
            field=models.CharField(choices=[('LOCAL_ADMIN', 'Local Admin'), ('SUBMITTER', 'Submitter'), ('MEDICAL_PARA_STAFF', 'Medical & Paramedical Staff'), ('VIEWER', 'Viewer'), ('TECHNICAL', 'Technical')], default='MEDICAL_PARA_STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='technicalstaff',
            name='role',
            field=models.CharField(choices=[('LOCAL_ADMIN', 'Local Admin'), ('SUBMITTER', 'Submitter'), ('MEDICAL_PARA_STAFF', 'Medical & Paramedical Staff'), ('VIEWER', 'Viewer'), ('TECHNICAL', 'Technical')], default='TECHNICAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerstaff',
            name='role',
            field=models.CharField(choices=[('LOCAL_ADMIN', 'Local Admin'), ('SUBMITTER', 'Submitter'), ('MEDICAL_PARA_STAFF', 'Medical & Paramedical Staff'), ('VIEWER', 'Viewer'), ('TECHNICAL', 'Technical')], default='VIEWER', max_length=20),
        ),
    ]
