# Generated by Django 4.2 on 2025-05-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0029_alter_administrativestaff_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_accord',
            field=models.BooleanField(default=False),
        ),
    ]
